# Generated by Django 3.2.7 on 2021-09-29 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SNS_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetmodel',
            name='content',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=150)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SNS_App.tweetmodel', verbose_name='紐づく記事')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
