# Generated by Django 3.2.7 on 2021-09-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNS_App', '0002_auto_20210929_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='カテゴリ名'),
        ),
    ]
