# Generated by Django 3.2.7 on 2021-11-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SNS_App', '0004_alter_tweetmodel_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Connection', # モデル名
            old_name='following',   # 変更前
            new_name='following2'    # 変更後
        )
        
    ]
