# Generated by Django 3.2.7 on 2021-11-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SNS_App', '0005_auto_20211111_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Connection', # モデル名
            old_name='following2',   # 変更前
            new_name='following'    # 変更後
        )
    ]
