# Generated by Django 3.2.7 on 2021-12-05 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SNS_App', '0006_auto_20211111_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetmodel',
            name='rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SNS_App.tweetmodel', verbose_name='紐づくツイート'),
        ),
    ]
