# Generated by Django 3.2.7 on 2021-12-05 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SNS_App', '0007_auto_20211206_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SNS_App.category', verbose_name='カテゴリ'),
        ),
    ]
