# Generated by Django 3.2.7 on 2021-12-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SNS_App', '0011_auto_20211228_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
    ]
