# Generated by Django 3.2.7 on 2021-12-29 01:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SNS_App', '0012_remove_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
