# Generated by Django 3.2.7 on 2021-12-29 02:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNS_App', '0014_remove_room_room_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_member',
            field=models.ManyToManyField(through='SNS_App.Entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
