# Generated by Django 3.2.7 on 2021-12-29 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SNS_App', '0015_room_room_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='joined_date',
        ),
    ]
