# Generated by Django 3.2.7 on 2021-12-31 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SNS_App', '0017_alter_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
