# Generated by Django 3.2.7 on 2022-01-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SNS_App', '0018_entries_joined_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetmodel',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
