# Generated by Django 3.2.7 on 2022-01-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNS_App', '0019_auto_20220103_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetmodel',
            name='ISBNcode',
            field=models.CharField(default=9784150123505, max_length=30),
            preserve_default=False,
        ),
    ]
