# Generated by Django 3.2.7 on 2022-01-14 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SNS_App', '0021_auto_20220108_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetmodel',
            name='ISBNcode',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tweetmodel',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tweetmodel',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tweetmodel',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='tweetmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='紐づくユーザー'),
        ),
    ]
