# Generated by Django 3.2.7 on 2022-01-14 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SNS_App', '0023_auto_20220114_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='tweetmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
