# Generated by Django 3.2.7 on 2022-01-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNS_App', '0024_auto_20220114_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetmodel',
            name='title',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
