# Generated by Django 3.2.7 on 2022-01-15 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SNS_App', '0027_alter_tweetmodel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetmodel',
            name='snsImage',
        ),
    ]
