# Generated by Django 3.2.7 on 2022-01-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNS_App', '0028_remove_tweetmodel_snsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetmodel',
            name='gametitle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
