# Generated by Django 3.2.7 on 2022-01-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNS_App', '0029_tweetmodel_gametitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemData',
            fields=[
                ('ISBNcode', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('gametitle', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('itemPrice', models.CharField(max_length=30)),
                ('itemUrl', models.CharField(max_length=100)),
                ('imageUrl', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='tweetmodel',
            name='gametitle',
        ),
    ]
