# Generated by Django 3.2.7 on 2022-01-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNS_App', '0030_auto_20220115_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('ISBNcode', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('itemPrice', models.CharField(max_length=30)),
                ('itemUrl', models.CharField(max_length=100)),
                ('imageUrl', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ItemData',
        ),
        migrations.RemoveField(
            model_name='tweetmodel',
            name='ISBNcode',
        ),
    ]
