# Generated by Django 3.2.7 on 2022-05-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SNS_App', '0033_alter_tweetmodel_book'),
    ]

    operations = [
         migrations.RenameField(
            model_name='Connection',
            old_name='follower', #例：変更したい変数名
            new_name='followed' #例：変更後の変数名
        )
    ]
