# Generated by Django 3.2.7 on 2022-05-16 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SNS_App', '0035_alter_connection_followed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='followed',
        ),
        migrations.AddField(
            model_name='connection',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
