from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('',SignupView.as_view(),name='signup'),
    path('login/',login_func,name='login'),
    path('logout/',logout_func,name='logout'),
    path('AuthenticateForEmailChange/',authenticate_for_email_change,name='AuthenticateForEmailChange'),
    path('EmailChange/<str:token>/',email_change,name='EmailChange'),
    path('EmailChange/<str:token>/Done/',email_change_done,name='EmailChangeDone'),
    path('PasswordChange/',password_change,name='PasswordChange'),
    path('PasswordChange/Done/',passeword_change_done,name='PasswordChangeDone'),
    path('PasswordReset/',password_reset,name='PasswordReset'),
    path('PasswordReset/Done/',password_reset_done,name='PasswordResetDone'),
    path('PasswordResetConfirm/<str:uidb64>/<str:token>/',password_reset_confirm,name='PasswordResetConfirm'),
    path('PasswordResetComplete/',password_reset_complete,name='PasswordResetComplete'),
    path('home/',HomeView.as_view(),name='home'),
    path('home2/',Home2View.as_view(),name='home2'),
    path('tweetCreate/<str:ISBNcode>',tweet_create,name='tweetCreate'),
    path('SelectItem/<str:ISBNcode>',select_item,name='SelectItem'), 
    path('TweetDelete/<int:tweet_pk>',tweet_del,name='TweetDelete'),
    path('CommentDelete/<int:comment_pk>',comment_del,name='CommentDelete'),
    path('profile_edit/<int:pk>',profile_editView.as_view(),name='profile_edit'),
    path('search_user/',SearchUserView.as_view(),name='search_user'),
    path('follower/<int:user_id>/',follower_show,name='follower'),
    path('following/<int:user_id>/',following_show,name='following'),
    path('tweet_like/',tweet_like_func, name='tweet_like'),
    path('comment_like/',comment_like_func, name='comment_like'),
    path('userPage/<int:pk>',userPageView.as_view(), name='userPage'),
    path('follow/',follow_func, name='follow'),
    path('CreateComment/<int:tweet_pk>',create_comment, name='CreateComment'),
    path('Chat/<int:user_id>', Chat.as_view(), name='Chat'),
    path('chat_room/<uuid:room_id>', chat_room, name='chat_room'),
    path('room/<int:pk>', room, name='room'),
    path('SearchItem/<str:From>',SearchItem.as_view(),name='SearchItem'),
    path('TweetOfItem/<str:ISBNcode>',TweetOfItemView.as_view(),name='TweetOfItem'),
]
